import type { Metadata } from "next";
import "./globals.css";
import QueryClientProvider from "@/shared/lib/QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />
      </head>
      <body className="font-sans antialiased">
        <QueryClientProvider>
          {/* 최대 넓이 570 -> 2280px 지정 */}
          <div className="min-h-screen max-w-570 mx-auto bg-ot-background flex flex-col">
            {children}
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
