import type { Metadata } from "next";
import { FloatingPlayer } from "@/features/player/components/FloatingPlayer";
import QueryClientProvider from "@/shared/lib/QueryClientProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />
      </head>
      <body className="font-sans antialiased">
        <QueryClientProvider>
          {/* 최대 넓이 570 -> 2280px 지정 */}
          <div className="bg-ot-background mx-auto flex min-h-screen max-w-570 flex-col">
            {children}
            <FloatingPlayer />
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
